{
    "topic": "App Commands Errors",
    "pageNumber": "1",
    "type": "App Error - Contribution Not Sent",
    "definition": {
        "text": "There was a problem trying to send your contribution to your fork of the Superalgos repository, or from your fork to the Superalgos/Superalgos main repository.",
        "updated": 1611129378492,
        "translations": [
            {
                "language": "DE",
                "text": "Es gab ein Problem beim Versuch, Ihren Beitrag (contribution) an Ihre Fork des Superalgos-Repositorys oder von Ihrer Fork an das Superalgos/Superalgos main repository zu senden.",
                "updated": 1637847176279
            },
            {
                "language": "RU",
                "text": "Возникла проблема при попытке отправить ваш вклад в ваш форк репозитория Superalgos или с вашего форка в главный репозиторий Superalgos / Superalgos.",
                "updated": 1638163298057
            },
            {
                "language": "TR",
                "text": "Katkınızı Superalgos deposunun çatalına veya çatalınızdan Superalgos/Superalgos ana deposuna göndermeye çalışırken bir sorun oluştu.",
                "updated": 1654392723354
            }
        ]
    },
    "paragraphs": [
        {
            "style": "Text",
            "text": "Check the following section for details on what may have happened. After you fix the issue that prevented the App Contribute Command to run, you may try again.",
            "updated": 1611152997869,
            "translations": [
                {
                    "language": "DE",
                    "text": "Lesen Sie den folgenden Abschnitt, um zu erfahren, was passiert sein könnte. Nachdem Sie das Problem behoben haben, das die Ausführung des App Contribute Command verhindert hat, können Sie es erneut versuchen.",
                    "updated": 1637847279708
                },
                {
                    "language": "RU",
                    "text": "Обратитесь к следующему разделу для получения подробной информации о том, что могло произойти. После устранения проблемы, из-за которой команда App Contribute Command не запускалась, вы можете попробовать еще раз.",
                    "updated": 1638163372898
                },
                {
                    "language": "TR",
                    "text": "Ne olmuş olabileceğine ilişkin ayrıntılar için aşağıdaki bölümü kontrol edin. App Contribute Komutunun çalışmasını engelleyen sorunu çözdükten sonra tekrar deneyebilirsiniz.",
                    "updated": 1654392731176,
                    "style": "Text"
                }
            ]
        },
        {
            "style": "Title",
            "text": "Error Info",
            "updated": 1611154606702,
            "translations": [
                {
                    "language": "RU",
                    "text": "Информация об ошибке",
                    "updated": 1638163397925
                },
                {
                    "language": "TR",
                    "text": "Hata Bilgisi",
                    "updated": 1654392737054,
                    "style": "Title"
                }
            ]
        },
        {
            "style": "Text",
            "text": "In the following section, you will find the information recorded when the error occurred.",
            "translations": [
                {
                    "language": "DE",
                    "text": "Im folgenden Abschnitt finden Sie die Informationen, die beim Auftreten des Fehlers aufgezeichnet wurden.",
                    "updated": 1637847305339
                },
                {
                    "language": "RU",
                    "text": "В следующем разделе вы найдете информацию, записанную при возникновении ошибки.",
                    "updated": 1638163423671
                },
                {
                    "language": "TR",
                    "text": "Aşağıdaki bölümde, hata oluştuğunda kaydedilen bilgileri bulacaksınız.",
                    "updated": 1654392742668,
                    "style": "Text"
                }
            ]
        },
        {
            "style": "Note",
            "text": "You will only see the information if you opened this page as a result of the error actually occurring.",
            "updated": 1611153032408,
            "translations": [
                {
                    "language": "DE",
                    "text": "Hinweis: Diese Informationen werden nur angezeigt, wenn Sie diese Seite geöffnet haben, weil der Fehler tatsächlich aufgetreten ist.",
                    "updated": 1637847343322
                },
                {
                    "language": "RU",
                    "text": "Вы увидите информацию только в том случае, если вы открыли эту страницу в результате действительно возникшей ошибки.",
                    "updated": 1638163451251
                },
                {
                    "language": "TR",
                    "text": "Bu bilgileri yalnızca hatanın gerçekten meydana gelmesinin bir sonucu olarak bu sayfayı açtıysanız göreceksiniz.",
                    "updated": 1654392748600,
                    "style": "Note"
                }
            ]
        },
        {
            "style": "Subtitle",
            "text": "Error Message",
            "translations": [
                {
                    "language": "DE",
                    "text": "Fehlermeldung (Error Message)",
                    "updated": 1637847408680
                },
                {
                    "language": "RU",
                    "text": "Сообщение об ошибке",
                    "updated": 1638163470882
                },
                {
                    "language": "TR",
                    "text": "Hata Mesajı",
                    "updated": 1654392754907,
                    "style": "Subtitle"
                }
            ]
        },
        {
            "style": "Text",
            "text": "The following is the Error Message of the Exception that occurred at the Client:",
            "translations": [
                {
                    "language": "DE",
                    "text": "Im Folgenden wird die Fehlermeldung der beim Client aufgetretenen Ausnahme angezeigt:",
                    "updated": 1637847389630
                },
                {
                    "language": "RU",
                    "text": "Ниже приводится сообщение об ошибке исключения, которое произошло на Client:",
                    "updated": 1638163508896
                },
                {
                    "language": "TR",
                    "text": "İstemcide meydana gelen İstisnanın Hata Mesajı aşağıdadır:",
                    "updated": 1654392760336,
                    "style": "Text"
                }
            ]
        },
        {
            "style": "Placeholder",
            "text": "errorMessage"
        },
        {
            "style": "Subtitle",
            "text": "Error Stack",
            "translations": [
                {
                    "language": "RU",
                    "text": "Стек ошибок",
                    "updated": 1638163536906
                },
                {
                    "language": "TR",
                    "text": "Hata Yığını",
                    "updated": 1654392765971,
                    "style": "Subtitle"
                }
            ]
        },
        {
            "style": "Text",
            "text": "The following is the Error Stack of the Exception that occurred at the Client:",
            "translations": [
                {
                    "language": "DE",
                    "text": "Im Folgenden ist der Error Stack der beim Client aufgetretenen Ausnahme dargestellt:",
                    "updated": 1637847442850
                },
                {
                    "language": "RU",
                    "text": "Ниже приводится стек ошибок исключения, возникшего на Client:",
                    "updated": 1638163563203
                },
                {
                    "language": "TR",
                    "text": "İstemcide meydana gelen İstisnanın Hata Yığını aşağıdadır:",
                    "updated": 1654392771665,
                    "style": "Text"
                }
            ]
        },
        {
            "style": "Placeholder",
            "text": "errorStack"
        },
        {
            "style": "Subtitle",
            "text": "Error Code",
            "translations": [
                {
                    "language": "RU",
                    "text": "Код ошибки",
                    "updated": 1638163579463
                },
                {
                    "language": "TR",
                    "text": "Hata Kodu",
                    "updated": 1654392777478,
                    "style": "Subtitle"
                }
            ]
        },
        {
            "style": "Text",
            "text": "The following is the Error Code of the Exception that occurred at the Client:",
            "translations": [
                {
                    "language": "DE",
                    "text": "Im Folgenden wird der Fehlercode der beim Client aufgetretenen Ausnahme angegeben:",
                    "updated": 1637847479023
                },
                {
                    "language": "RU",
                    "text": "Ниже приведен код ошибки исключения, возникшего на Client:",
                    "updated": 1638163601482
                },
                {
                    "language": "TR",
                    "text": "İstemcide meydana gelen İstisnanın Hata Kodu aşağıdadır:",
                    "updated": 1654392783415,
                    "style": "Text"
                }
            ]
        },
        {
            "style": "Placeholder",
            "text": "errorCode"
        },
        {
            "style": "Subtitle",
            "text": "Error Details",
            "updated": 1611154543778,
            "translations": [
                {
                    "language": "RU",
                    "text": "Детали ошибки",
                    "updated": 1638163624397
                },
                {
                    "language": "TR",
                    "text": "Hata Detayları",
                    "updated": 1654392790569,
                    "style": "Subtitle"
                }
            ]
        },
        {
            "style": "Text",
            "text": "The following are all the Error details of the Exception that occurred at the Client:",
            "updated": 1611154675224,
            "translations": [
                {
                    "language": "DE",
                    "text": "Im Folgenden werden alle Fehlerdetails der beim Client aufgetretenen Ausnahme aufgeführt:",
                    "updated": 1637847501074
                },
                {
                    "language": "RU",
                    "text": "Ниже приведены все подробности об ошибке исключения, которое произошло на Client:",
                    "updated": 1638163644557
                },
                {
                    "language": "TR",
                    "text": "Aşağıda, İstemcide meydana gelen İstisnanın tüm Hata ayrıntıları yer almaktadır:",
                    "updated": 1654392796294,
                    "style": "Text"
                }
            ]
        },
        {
            "style": "Placeholder",
            "text": "errorDetails",
            "updated": 1611154555419
        },
        {
            "style": "Text",
            "text": ""
        }
    ]
}