{
    "topic": "TS Process Errors",
    "pageNumber": "1",
    "type": "TS Process Error - Unexpected Error",
    "definition": {
        "text": "There was an unexpected error and the process was shut down.",
        "updated": 1611413113338,
        "translations": [
            {
                "language": "RU",
                "text": "Возникла непредвиденная ошибка, и процесс был остановлен.",
                "updated": 1645629426928
            },
            {
                "language": "TR",
                "text": "Özet: Beklenmeyen bir hata oluştu ve işlem durduruldu.",
                "updated": 1647096176839
            }
        ]
    },
    "paragraphs": [
        {
            "style": "Text",
            "text": "While running at the TS, the process encountered and unexpected error that forced the TS to shut the process down. The Task may still be running other unaffected processes, but if all the processes stop running or this was the only process under the Task, then the Task may have stopped too.",
            "updated": 1611413246602,
            "translations": [
                {
                    "language": "TR",
                    "text": "TS'de çalışırken, hatalı bir işlemle karşılaşıldı ve TS'yi işlem kapatmaya zorlayan beklenmeyen bir hata oluştu. Görev ( Task ), etkilenmeyen diğer işlemleri çalıştırmaya devam ediyor olabilir, ancak tüm işlemlerin çalışması durursa veya Görev altındaki tek işlem buysa, Görev de durmuş olabilir.",
                    "updated": 1647096307479
                }
            ]
        },
        {
            "style": "Error",
            "text": "Unexpected Error",
            "translations": [
                {
                    "language": "TR",
                    "text": "Hata: Beklenmeyen Hata ( Unexpected Error )",
                    "updated": 1647096334960
                }
            ]
        },
        {
            "style": "Title",
            "text": "Error Info",
            "updated": 1611258020914,
            "translations": [
                {
                    "language": "RU",
                    "text": "Информация об ошибке",
                    "updated": 1645629461558
                },
                {
                    "language": "TR",
                    "text": "Hata Bilgisi",
                    "updated": 1647096365368
                }
            ]
        },
        {
            "style": "Text",
            "text": "In the following section, you will find the information recorded when the error occurred.",
            "translations": [
                {
                    "language": "RU",
                    "text": "В следующем разделе вы найдете информацию, записанную при возникновении ошибки.",
                    "updated": 1645629470286
                },
                {
                    "language": "TR",
                    "text": "Aşağıdaki bölümde, hata oluştuğunda kaydedilen bilgileri bulacaksınız.",
                    "updated": 1647096374012
                }
            ]
        },
        {
            "style": "Success",
            "text": "You will only see the information if you opened this page as a result of the error actually occurring.",
            "updated": 1611258030660,
            "translations": [
                {
                    "language": "RU",
                    "text": "Вы увидите информацию только в том случае, если вы открыли эту страницу в результате того, что ошибка действительно произошла.",
                    "updated": 1645629479296
                },
                {
                    "language": "TR",
                    "text": "İpucu: Bilgileri yalnızca bu sayfayı gerçekten oluşan hatanın bir sonucu olarak açtıysanız göreceksiniz.",
                    "updated": 1647096381849
                }
            ]
        },
        {
            "style": "Subtitle",
            "text": "Error Message",
            "translations": [
                {
                    "language": "TR",
                    "text": "Hata mesajı",
                    "updated": 1647096398267
                }
            ]
        },
        {
            "style": "Text",
            "text": "The following is the Error Message of the Exception that occurred at the TS:",
            "translations": [
                {
                    "language": "RU",
                    "text": "Ниже приведено сообщение об ошибке исключения, произошедшего в TS:",
                    "updated": 1645629487146
                },
                {
                    "language": "TR",
                    "text": "TS'de meydana gelen İstisnanın Hata Mesajı aşağıdadır:",
                    "updated": 1647096408765
                }
            ]
        },
        {
            "style": "Placeholder",
            "text": "errorMessage"
        },
        {
            "style": "Subtitle",
            "text": "Error Stack",
            "translations": [
                {
                    "language": "TR",
                    "text": "Hata Yığını",
                    "updated": 1647096432568
                }
            ]
        },
        {
            "style": "Text",
            "text": "The following is the Error Stack of the Exception that occurred at the TS:",
            "translations": [
                {
                    "language": "RU",
                    "text": "Ниже приведен стек ошибок исключения, произошедшего в TS:",
                    "updated": 1645629494990
                },
                {
                    "language": "TR",
                    "text": "TS'de meydana gelen İstisnanın Hata Yığını aşağıdadır:",
                    "updated": 1647096437393
                }
            ]
        },
        {
            "style": "Placeholder",
            "text": "errorStack"
        },
        {
            "style": "Subtitle",
            "text": "Error Code",
            "translations": [
                {
                    "language": "TR",
                    "text": "Hata Kodu",
                    "updated": 1647096459797
                }
            ]
        },
        {
            "style": "Text",
            "text": "The following is the Error Code of the Exception that occurred at the TS:",
            "translations": [
                {
                    "language": "RU",
                    "text": "Ниже приведен код ошибки исключения, произошедшего в TS:",
                    "updated": 1645629500864
                },
                {
                    "language": "TR",
                    "text": "TS'de meydana gelen İstisnanın Hata Kodu aşağıdadır:",
                    "updated": 1647096463538
                }
            ]
        },
        {
            "style": "Placeholder",
            "text": "errorCode"
        },
        {
            "style": "Subtitle",
            "text": "Error Details",
            "translations": [
                {
                    "language": "TR",
                    "text": "Hata detayları",
                    "updated": 1647096477685
                }
            ]
        },
        {
            "style": "Text",
            "text": "The following are all the Error details of the Exception that occurred at the TS:",
            "translations": [
                {
                    "language": "RU",
                    "text": "Ниже перечислены все детали ошибки исключения, произошедшего в TS:",
                    "updated": 1645629506766
                },
                {
                    "language": "TR",
                    "text": "Aşağıdakiler, TS'de meydana gelen İstisnanın tüm Hata ayrıntılarıdır:",
                    "updated": 1647096485022
                }
            ]
        },
        {
            "style": "Placeholder",
            "text": "errorDetails"
        },
        {
            "style": "Text",
            "text": ""
        }
    ]
}